#Drafting

## Specific Aims

Psychological resilience can be defined as one’s ability to successfully cope in the face of stress and trauma and either maintain a pre-stress level of psychological and physiological functioning or quickly return to it. Studies of resilience have identified it to be a multifaceted trait influenced by factors such as social support, socioeconomic status, successful termination of stress responses, and developmental timing of stress. Resilience has also been identified to be moderately heritable, evidencing a genetic component to the trait. While there is support for the influence of genetics in resilience, the genetic variants that contribute to the observed heritability are not well understood. In order to address this gap in knowledge, I propose a robust, large-scale genome-wide association study (GWAS) of resilience as well as follow-up analyses to investigate the polygenic nature of resilience further. In order to accomplish the proposed research, I will make use of secondary data available through UK Biobank. UK Biobank is a large population-based cohort that consists of survey data, which will allow for the construction of the resilience measure, as well as provide the genetic data needed to perform the GWAS. In addition, the identification of genetic variants will allow for further investigation of the extent to which their associated genes aggregate within influential pathways. Importantly, understanding the genetics of resilience can also contribute to the development of mechanism-focused interventions for those who are at increased risk for the development of psychopathology.

In order to accomplish the goals of this project, I propose three specific aims:

**Aim 1: Validate Scoring Algorithm to Convert Widely Available Psychological Assessments into Resiliency via Comparison with Established Measure Using a Large Online Sample**

As resilience is not directly measured in any existing large-scale genetic dataset, the first aim of the project is to validate my operational definition of resilience. Taking steps to validate the measure helps to ensure the GWAS will be as robust as possible, as measurement inaccuracies can result in unreliable results.

Resilience will be operationalized as negative affect residualized over stress and trauma. These measures will be obtained from survey data available through UK Biobank. In order to validate this construct of resilience, I will test it within a sample of the general population and assess how strongly it correlates with the Connor-Davidson Resilience Scale, the most commonly used measure of resilience. I hypothesize that they will be strongly correlated based on my recent exploratory study of polygenic proxies of resilience, which found this to be a robust operationalization of resilience.

**Aim 2: Perform a Genome-Wide Association Study of Resilience in the UK Biobank (N > 150,000)**

In order to identify genetic variants associated with resilience, I will perform a genome-wide association study (GWAS). To date, only one GWAS of resilience has been done but was limited by its sample size and generalizability. The proposed GWAS of resilience will improve on the one previously performed by leveraging a large sample size (N > 150,000) and a population-based cohort. The UK Biobank data will undergo seven specific quality control procedures before conducting the genome-wide association analyses. The results of the GWAS will identify which genetic variants (i.e., single nucleotide polymorphisms) are significantly associated with resilience at P < 5×10−8. These significant single nucleotide polymorphisms (SNPs) will then undergo further analyses in aim three, to better understand their relationship with resilience.

**Aim 3: Follow-up Analyses of GWAS Results to Investigate Biological Relevance and Polygenic Nature**

Following the GWAS of resilience, analyses will be performed to provide context and a greater understanding of the SNPs that were identified as being significantly associated with resilience. In this third aim, two follow-up analyses will be conducted. The first of which will be a SNP annotation, to provide genetic context for the SNPs. The second will be the construction of a polygenic risk score. In an independent replication sample, polygenic scores will be constructed by aggregating resilience associated SNPs to produce a single polygenic risk score of resilience. Once constructed, this score can then be used to predict individual resiliency.

Together, these aims will further our understanding of the genetics of resilience and move towards potential biological mechanisms that can be acted on to produce better mental health outcomes in those exposed to stress or trauma.

##Chapter 1: Introduction

Brief overview 

##Chapter 2: Background and Significance 

###Defining Psychological Resilience

###Current understanding of the Genetics of Resilience

###Gap in knowledge/Dearth of research

###Proposal

##Chapter 3: Study 1 - Validation of Resilience Measure

###Challenges to Resilience Measurment

###Importance of Measurement & Validation

### Approach for the proposed study

##Chapter 4: Study 2 - GWAS of Resilience

###Rationale for a GWAS of Resilience

Echo parts from Section \@ref(S:Gap in knowledge/Dearth of research) 

###Approach for proposed study

##Chapter 5: Study 3 - Biological & Functional Annotation 

##Chapter 6: ????


